version: '3.9'
services:
  mariadb:
    image: mariadb:11.1.2
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exampledb
    volumes:
      - tarea8_volume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - tarea8_network

  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - tarea8_volume:/data/db
    ports:
      - "27017:27017"
    networks:
      - tarea8_network

  mongo-express:
    image: mongo-express:latest
    container_name: express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin123
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
    networks:
      - tarea8_network

  tomcat1:
    image: tomcat:10.1.9-jdk17
    container_name: tomcat1
    ports:
      - "8091:8080"
    volumes:
      - ./assets/sample.war:/usr/local/tomcat/webapps/sample.war
    networks:
      - tarea8_network


  tomcat2:
    image: tomcat:10.1.9-jdk17
    container_name: tomcat2
    ports:
      - "8092:8080"
    volumes:
      - ./assets/sample.war:/usr/local/tomcat/webapps/sample.war
    networks:
      - tarea8_network

  cloudbeaver:
    image: dbeaver/cloudbeaver:23.3.0
    container_name: cloudbeaver
    ports:
      - "8978:8978"
    networks:
      - tarea8_network

volumes:
  tarea8_volume:
networks:
  tarea8_network: